// Access to the committed project fixture.
//
// `fixtures/projects/E2E Fixture/` is a real project saved by Silverdaw 1.4.1 and
// then frozen. It is the tier's backward-compatibility canary: CONTEXT.md makes it a
// CRITICAL constraint that saved projects keep opening across every update, and the
// only way to hold that line is to keep reading an artefact an older build actually
// wrote.
//
// Never regenerate it. A fixture regenerated by the current build proves only that
// today's writer agrees with today's reader, which is precisely the bug class this
// is meant to catch.
//
// It is portable by design: the audio sits inside the project folder, so the engine
// stores its path relative to that folder (ProjectFile.cpp `kPortablePathKeys`) and
// the fixture carries no machine-specific absolute path.

import { cpSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { makeTrackedTempDir } from './tempDirs'

const HERE = dirname(fileURLToPath(import.meta.url))

/** Project folder name, which is also the display name Silverdaw shows for it. */
export const FIXTURE_PROJECT_NAME = 'E2E Fixture'

/** Audio the fixture references, by a path relative to the project folder. */
export const FIXTURE_AUDIO_FILE = 'fixture-tone.wav'

/**
 * Master volume the fixture stores, as the transport bar renders it. A new project
 * opens at this level, so a load that silently lost the value would still look
 * plausible — asserting it catches a settings-loss regression that no visual check
 * would notice.
 */
export const FIXTURE_MASTER_VOLUME = 'Master volume: -10.0 dB'

/**
 * Copies the fixture project to a temporary directory and returns the path of its
 * `.silverdaw` file.
 *
 * Opening a project writes into its folder (metadata, cover art, view state), so a
 * spec must never open the committed copy in place: doing so would dirty the working
 * tree and leave later runs testing a mutated artefact rather than the frozen one.
 */
export function copyProjectFixture(): string {
  const dir = makeTrackedTempDir('fixture')
  const projectDir = join(dir, FIXTURE_PROJECT_NAME)
  cpSync(join(HERE, '..', 'fixtures', 'projects', FIXTURE_PROJECT_NAME), projectDir, {
    recursive: true
  })
  return join(projectDir, `${FIXTURE_PROJECT_NAME}.silverdaw`)
}
