# Discovers individual backend test cases so each one appears as its own CTest
# test (and its own row in the VS Code Testing panel), mirroring how Vitest
# lists frontend tests. Runs the freshly-built harness with `--list` and writes
# one `add_test` per case, each invoking the harness with `--run "<name>"`.
#
# Invoked as a POST_BUILD step: cmake -D TEST_EXECUTABLE=... -D CTEST_FILE=... -P
# SilverdawDiscoverTests.cmake

if(NOT DEFINED TEST_EXECUTABLE OR NOT DEFINED CTEST_FILE)
    message(FATAL_ERROR "SilverdawDiscoverTests: TEST_EXECUTABLE and CTEST_FILE are required")
endif()

execute_process(
    COMMAND "${TEST_EXECUTABLE}" --list
    OUTPUT_VARIABLE _list_output
    RESULT_VARIABLE _list_result
)

if(NOT _list_result EQUAL 0)
    message(FATAL_ERROR "SilverdawDiscoverTests: '${TEST_EXECUTABLE} --list' failed (${_list_result})")
endif()

# Normalise line endings, then split into individual names.
string(REPLACE "\r" "" _list_output "${_list_output}")
string(REPLACE "\n" ";" _names "${_list_output}")

set(_content "# Generated by SilverdawDiscoverTests.cmake — do not edit.\n")
foreach(_name IN LISTS _names)
    string(STRIP "${_name}" _name)
    if(_name STREQUAL "")
        continue()
    endif()
    # Escape backslashes and quotes for safe embedding in the generated file.
    string(REPLACE "\\" "\\\\" _escaped "${_name}")
    string(REPLACE "\"" "\\\"" _escaped "${_escaped}")
    string(APPEND _content
        "add_test(\"${_escaped}\" \"${TEST_EXECUTABLE}\" --run \"${_escaped}\")\n")
endforeach()

file(WRITE "${CTEST_FILE}" "${_content}")
